version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      dotnet:
        patterns: ["*"]
    ignore:
      - dependency-name: Microsoft.OpenApi
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: /src/RuzoSolutions.Web
    schedule:
      interval: weekly
    groups:
      frontend:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
